# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1356, 770)
        Form.setMinimumSize(QtCore.QSize(1356, 770))
        Form.setMaximumSize(QtCore.QSize(1356, 770))
        font = QtGui.QFont()
        font.setFamily("黑体")
        Form.setFont(font)
        self.graphicsView_pre_front = QtWidgets.QGraphicsView(Form)
        self.graphicsView_pre_front.setGeometry(QtCore.QRect(20, 81, 251, 211))
        self.graphicsView_pre_front.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_pre_front.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_pre_front.setObjectName("graphicsView_pre_front")
        self.graphicsView_pre_back = QtWidgets.QGraphicsView(Form)
        self.graphicsView_pre_back.setGeometry(QtCore.QRect(20, 341, 251, 211))
        self.graphicsView_pre_back.setAutoFillBackground(False)
        self.graphicsView_pre_back.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_pre_back.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_pre_back.setObjectName("graphicsView_pre_back")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(300, 50, 401, 651))
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 399, 649))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 670, 121, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 40, 101, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 300, 111, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 560, 101, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 620, 111, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(300, 710, 191, 45))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_deleteimg = QtWidgets.QPushButton(Form)
        self.pushButton_deleteimg.setGeometry(QtCore.QRect(510, 710, 191, 45))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_deleteimg.setFont(font)
        self.pushButton_deleteimg.setObjectName("pushButton_deleteimg")
        self.graphicsView_slc_front = QtWidgets.QGraphicsView(Form)
        self.graphicsView_slc_front.setGeometry(QtCore.QRect(740, 50, 600, 551))
        self.graphicsView_slc_front.setMouseTracking(True)
        self.graphicsView_slc_front.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_slc_front.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.graphicsView_slc_front.setBackgroundBrush(brush)
        self.graphicsView_slc_front.setDragMode(QtWidgets.QGraphicsView.NoDrag)
        self.graphicsView_slc_front.setObjectName("graphicsView_slc_front")
        self.pushButton_7zhezhou = QtWidgets.QPushButton(Form)
        self.pushButton_7zhezhou.setGeometry(QtCore.QRect(740, 710, 191, 45))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_7zhezhou.setFont(font)
        self.pushButton_7zhezhou.setObjectName("pushButton_7zhezhou")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(710, 210, 31, 211))
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.listWidget_class = QtWidgets.QComboBox(Form)
        self.listWidget_class.setGeometry(QtCore.QRect(120, 570, 151, 31))
        self.listWidget_class.setObjectName("listWidget_class")
        self.listWidget_size = QtWidgets.QComboBox(Form)
        self.listWidget_size.setGeometry(QtCore.QRect(120, 620, 151, 31))
        self.listWidget_size.setObjectName("listWidget_size")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 730, 151, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox.setGeometry(QtCore.QRect(740, 610, 71, 41))
        self.doubleSpinBox.setMinimum(0.0)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(1010, 610, 161, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(820, 610, 171, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 670, 121, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(770, 660, 301, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(1090, 660, 51, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(770, 685, 371, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(740, 690, 54, 12))
        self.label_9.setObjectName("label_9")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(740, 665, 54, 12))
        self.label_6.setObjectName("label_6")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(1180, 610, 161, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setGeometry(QtCore.QRect(1180, 610, 161, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(1160, 660, 181, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_8_paiban = QtWidgets.QPushButton(Form)
        self.pushButton_8_paiban.setGeometry(QtCore.QRect(940, 710, 191, 45))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_8_paiban.setFont(font)
        self.pushButton_8_paiban.setObjectName("pushButton_8_paiban")
        self.pushButton_9_qiepian = QtWidgets.QPushButton(Form)
        self.pushButton_9_qiepian.setGeometry(QtCore.QRect(1140, 710, 201, 45))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_9_qiepian.setFont(font)
        self.pushButton_9_qiepian.setObjectName("pushButton_9_qiepian")

        self.retranslateUi(Form)
        self.pushButton_3.clicked.connect(Form.import_mat)
        self.pushButton_5.clicked.connect(Form.add_image)
        self.pushButton_deleteimg.clicked.connect(Form.delete_image)
        self.listWidget_class.currentIndexChanged['QString'].connect(Form.select_model)
        self.listWidget_size.currentIndexChanged['QString'].connect(Form.select_size)
        self.doubleSpinBox.valueChanged['double'].connect(Form.change_scale)
        self.pushButton_10.clicked.connect(Form.default_slice)
        self.pushButton_11.clicked.connect(Form.free_slice)
        self.pushButton_7zhezhou.clicked.connect(Form.output_rander)
        self.lineEdit.editingFinished.connect(Form.textDir)
        self.lineEdit_2.editingFinished.connect(Form.textCode)
        self.pushButton.clicked.connect(Form.chooseDir)
        self.pushButton_14.clicked.connect(Form.select_color)
        self.pushButton_8_paiban.clicked.connect(Form.output_compose)
        self.pushButton_9_qiepian.clicked.connect(Form.output_slice)
        self.pushButton_13.clicked.connect(Form.rand_btn)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "cloth"))
        self.pushButton_3.setText(_translate("Form", "导入"))
        self.label.setText(_translate("Form", "正面褶皱"))
        self.label_2.setText(_translate("Form", "反面褶皱"))
        self.label_4.setText(_translate("Form", "衣服种类"))
        self.label_5.setText(_translate("Form", "衣服尺码"))
        self.pushButton_5.setText(_translate("Form", "添加图片"))
        self.pushButton_deleteimg.setText(_translate("Form", "删除图片"))
        self.pushButton_7zhezhou.setText(_translate("Form", "导出褶皱图"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:11pt; font-weight:600;\">处</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:11pt; font-weight:600;\">理</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:11pt; font-weight:600;\">区</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "版本：1.5.0"))
        self.pushButton_10.setText(_translate("Form", "默认排版"))
        self.pushButton_11.setText(_translate("Form", "自由排版"))
        self.pushButton_4.setText(_translate("Form", "扩展尺码"))
        self.pushButton.setText(_translate("Form", "选择"))
        self.label_9.setText(_translate("Form", "编号"))
        self.label_6.setText(_translate("Form", "目录"))
        self.pushButton_12.setText(_translate("Form", "渲染模式"))
        self.pushButton_13.setText(_translate("Form", "渲染"))
        self.pushButton_14.setText(_translate("Form", "背景切换"))
        self.pushButton_8_paiban.setText(_translate("Form", "导出排版图"))
        self.pushButton_9_qiepian.setText(_translate("Form", "导出切片图"))
