# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI2.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1356, 773)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        #Form.setMaximumSize(QtCore.QSize(999999, 999999))
        font = QtGui.QFont()
        font.setFamily("黑体")
        Form.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_8_paiban = QtWidgets.QPushButton(Form)
        self.pushButton_8_paiban.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_8_paiban.setFont(font)
        self.pushButton_8_paiban.setObjectName("pushButton_8_paiban")
        self.gridLayout.addWidget(self.pushButton_8_paiban, 9, 9, 1, 3)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 6, 1, 1)
        self.pushButton_7zhezhou = QtWidgets.QPushButton(Form)
        self.pushButton_7zhezhou.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_7zhezhou.setFont(font)
        self.pushButton_7zhezhou.setObjectName("pushButton_7zhezhou")
        self.gridLayout.addWidget(self.pushButton_7zhezhou, 9, 6, 1, 3)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 6, 2, 2, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 9, 0, 1, 3)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 6, 7, 1, 4)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 6, 0, 2, 2)
        self.listWidget_size = QtWidgets.QComboBox(Form)
        self.listWidget_size.setMinimumSize(QtCore.QSize(0, 30))
        self.listWidget_size.setObjectName("listWidget_size")
        self.gridLayout.addWidget(self.listWidget_size, 5, 1, 1, 2)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 193, 707))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 3, 8, 2)
        self.graphicsView_pre_front = QtWidgets.QGraphicsView(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_pre_front.sizePolicy().hasHeightForWidth())
        self.graphicsView_pre_front.setSizePolicy(sizePolicy)
        self.graphicsView_pre_front.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_pre_front.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_pre_front.setObjectName("graphicsView_pre_front")
        self.gridLayout.addWidget(self.graphicsView_pre_front, 1, 0, 1, 3)
        self.graphicsView_slc_front = QtWidgets.QGraphicsView(Form)
        self.graphicsView_slc_front.setMouseTracking(True)
        self.graphicsView_slc_front.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_slc_front.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.graphicsView_slc_front.setBackgroundBrush(brush)
        self.graphicsView_slc_front.setDragMode(QtWidgets.QGraphicsView.NoDrag)
        self.graphicsView_slc_front.setObjectName("graphicsView_slc_front")
        self.gridLayout.addWidget(self.graphicsView_slc_front, 0, 6, 5, 8)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 6, 1, 1)
        self.listWidget_class = QtWidgets.QComboBox(Form)
        self.listWidget_class.setMinimumSize(QtCore.QSize(0, 30))
        self.listWidget_class.setObjectName("listWidget_class")
        self.gridLayout.addWidget(self.listWidget_class, 4, 1, 1, 2)
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 9, 3, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 5, 8, 1, 2)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.doubleSpinBox.setMinimum(0.0)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 5, 6, 1, 2)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 2)
        self.pushButton_9_qiepian = QtWidgets.QPushButton(Form)
        self.pushButton_9_qiepian.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_9_qiepian.setFont(font)
        self.pushButton_9_qiepian.setObjectName("pushButton_9_qiepian")
        self.gridLayout.addWidget(self.pushButton_9_qiepian, 9, 12, 1, 2)
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 11, 1, 1)
        self.pushButton_deleteimg = QtWidgets.QPushButton(Form)
        self.pushButton_deleteimg.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_deleteimg.setFont(font)
        self.pushButton_deleteimg.setObjectName("pushButton_deleteimg")
        self.gridLayout.addWidget(self.pushButton_deleteimg, 9, 4, 1, 1)
        self.graphicsView_pre_back = QtWidgets.QGraphicsView(Form)
        self.graphicsView_pre_back.setAutoFillBackground(False)
        self.graphicsView_pre_back.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_pre_back.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_pre_back.setObjectName("graphicsView_pre_back")
        self.gridLayout.addWidget(self.graphicsView_pre_back, 3, 0, 1, 3)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setMinimumSize(QtCore.QSize(30, 200))
        self.textBrowser.setMaximumSize(QtCore.QSize(30, 200))
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 5, 3, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 7, 7, 1, 5)
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 6, 12, 1, 2)
        self.listWidget_size_3 = QtWidgets.QComboBox(Form)
        self.listWidget_size_3.setObjectName("listWidget_size_3")
        self.gridLayout.addWidget(self.listWidget_size_3, 7, 12, 1, 2)
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 5, 10, 1, 2)
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 5, 12, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 5, 13, 1, 1)

        self.retranslateUi(Form)
        self.pushButton_3.clicked.connect(Form.import_mat)
        self.pushButton_5.clicked.connect(Form.add_image)
        self.pushButton_deleteimg.clicked.connect(Form.delete_image)
        self.listWidget_class.currentIndexChanged['QString'].connect(Form.select_model)
        self.listWidget_size.currentIndexChanged['QString'].connect(Form.select_size)
        self.doubleSpinBox.valueChanged['double'].connect(Form.change_scale)
        self.pushButton_10.clicked.connect(Form.default_slice)
        self.pushButton_11.clicked.connect(Form.free_slice)
        self.pushButton_7zhezhou.clicked.connect(Form.output_rander)
        self.lineEdit.editingFinished.connect(Form.textDir)
        self.lineEdit_2.editingFinished.connect(Form.textCode)
        self.pushButton.clicked.connect(Form.chooseDir)
        self.pushButton_14.clicked.connect(Form.select_color)
        self.pushButton_8_paiban.clicked.connect(Form.output_compose)
        self.pushButton_9_qiepian.clicked.connect(Form.output_slice)
        self.pushButton_13.clicked.connect(Form.rand_btn)
        self.listWidget_size_3.currentIndexChanged['QString'].connect(Form.select_size)
        self.pushButton_2.clicked.connect(Form.rand_slice)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "cloth"))
        self.label.setText(_translate("Form", "正面褶皱"))
        self.pushButton_8_paiban.setText(_translate("Form", "导出排版图"))
        self.label_9.setText(_translate("Form", "编号"))
        self.pushButton_7zhezhou.setText(_translate("Form", "导出褶皱图"))
        self.pushButton_4.setText(_translate("Form", "扩展尺码"))
        self.label_3.setText(_translate("Form", "版本：1.5.2"))
        self.pushButton_3.setText(_translate("Form", "导入"))
        self.label_6.setText(_translate("Form", "目录"))
        self.pushButton_5.setText(_translate("Form", "添加图片"))
        self.pushButton_11.setText(_translate("Form", "自由排版"))
        self.label_2.setText(_translate("Form", "反面褶皱"))
        self.pushButton_9_qiepian.setText(_translate("Form", "导出切片图"))
        self.label_5.setText(_translate("Form", "衣服尺码"))
        self.pushButton.setText(_translate("Form", "选择"))
        self.pushButton_deleteimg.setText(_translate("Form", "删除图片"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:11pt; font-weight:600;\">处</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:11pt; font-weight:600;\">理</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:11pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:11pt; font-weight:600;\">区</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "衣服种类"))
        self.pushButton_14.setText(_translate("Form", "背景切换"))
        self.pushButton_10.setText(_translate("Form", "默认排版"))
        self.pushButton_13.setText(_translate("Form", "渲染褶皱"))
        self.pushButton_2.setText(_translate("Form", "渲染切片"))
